In [1]:
import pandas as pd 
import numpy as np

In [7]:
df1 = pd.read_csv('datasets/data2.csv')
df3 = pd.read_csv('datasets\American_Movies_2019_to_2025_Master.csv')
df2 = pd.read_csv('datasets/data3.csv')

In [8]:
df1

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,duration,movie_title,language,imdb_score,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,178.0,avatar,English,7.9,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,169.0,pirates of the caribbean: at world's end,English,7.1,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,148.0,spectre,English,6.8,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,164.0,the dark knight rises,English,8.5,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,0.0,star wars: episode vii - the force awakens ...,unknown,7.1,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...,...,...,...
5353,Jim Strouse,Jessica Williams,Chris O'Dowd,Keith Stanfield,Romance Comedy,83.0,the incredible jessica james,English,6.2,Jessica Williams Chris O'Dowd Keith Stanfield ...
5354,Farhad Mann,Adelaide Kane,Benjamin Hollingsworth,Jean Louisa Kelly,Romance,86.0,can't buy my love,English,7.0,Adelaide Kane Benjamin Hollingsworth Jean Loui...
5355,Hannaleena Hauru,Inka Haapamäki,Rosa Honkonen,Tiitus Rantala,Romance Comedy,90.0,thick lashes of lauri mäntyvaara,Finnish,8.0,Inka Haapamäki Rosa Honkonen Tiitus Rantala Ha...
5356,Jonathan A. Rosenbaum,Lou Diamond Phillips,Wallace Shawn,Gina Holden,Crime Comedy Action Family,97.0,cop and a half: new recruit,English,6.0,Lou Diamond Phillips Wallace Shawn Gina Holden...
5357,Ravi Udyawar,Sridevi Kapoor,Sajal Ali,Akshaye Khanna,Crime Drama Thriller,146.0,mom,Hindi,6.6,Sridevi Kapoor Sajal Ali Akshaye Khanna Ravi U...

In [11]:
df2.columns

Index(['Unnamed: 0', 'director_name', 'actor_1_name', 'actor_2_name',
       'actor_3_name', 'genres', 'movie_title', 'language', 'duration',
       'imdb_score', 'comb'],
      dtype='object')

In [14]:
new_df2 = df2.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title','language','duration','imdb_score', 'comb']]
new_df2

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,language,duration,imdb_score,comb
0,Adam Robitel,Lin Shaye,Angus Sampson,Leigh Whannell,Horror Thriller,insidious: the last key,English,103.0,6.3,Lin Shaye Angus Sampson Leigh Whannell Adam Ro...
1,Christopher Radcliff (director/screenplay); La...,Alex Pettyfer,James Freedson-Jackson,Emily Althaus,Drama Mystery,the strange ones,English,14.0,6.9,Lauren Wolkstein (director); Alex Pettyfer Jam...
2,Jaume Collet-Serra,Liam Neeson,Vera Farmiga,Patrick Wilson,Action Thriller Mystery,the commuter,English,104.0,6.4,Liam Neeson Vera Farmiga Patrick Wilson Jaume ...
3,Babak Najafi,Taraji P. Henson,Jahi Di'Allo Winston,Billy Brown,Thriller Action Crime,proud mary,English,88.0,5.5,Taraji P. Henson Jahi Di'Allo Winston Billy Br...
4,Brett Donowho,Bruce Willis,Cole Hauser,Shawn Ashmore,Action Crime Thriller,acts of violence,English,86.0,5.6,Bruce Willis Cole Hauser Shawn Ashmore Brett D...
...,...,...,...,...,...,...,...,...,...,...
246,Peter Segal,Jennifer Lopez,Leah Remini,Vanessa Hudgens,Romance Comedy,second act,English,103.0,6.3,Jennifer Lopez Leah Remini Vanessa Hudgens Pet...
247,Etan Cohen,Will Ferrell,John C. Reilly,Rebecca Hall,Comedy Mystery Crime,holmes & watson,English,90.0,4.3,Will Ferrell John C. Reilly Rebecca Hall Etan ...
248,Adam McKay,Christian Bale,Amy Adams,Steve Carell,Drama Comedy,vice,English,132.0,7.0,Christian Bale Amy Adams Steve Carell Adam McK...
249,Mimi Leder,Felicity Jones,Armie Hammer,Justin Theroux,Drama History,on the basis of sex,English,120.0,7.3,Felicity Jones Armie Hammer Justin Theroux Mim...
250,Karyn Kusama,Nicole Kidman,Sebastian Stan,Toby Kebbell,Thriller Crime Drama Action,destroyer,English,121.0,5.9,Nicole Kidman Sebastian Stan Toby Kebbell Kary...

In [48]:
df3 = pd.read_csv('datasets\American_Movies_2019_to_2025_Master.csv')

In [49]:
df3.columns

Index(['movie_title', 'Release_Year', 'director_name', 'actor_1_name',
       'actor_2_name', 'actor_3_name', 'genres', 'duration', 'language',
       'tmdb_score'],
      dtype='object')

In [50]:
title_duplicates = df3.duplicated(subset=['movie_title']).sum()
print(f"I found {title_duplicates} duplicate movie titles!")

I found 86 duplicate movie titles!

In [51]:
df3.duplicated().sum()

np.int64(72)

In [52]:
df3.drop_duplicates(subset=['movie_title'], keep='first', inplace=True)
df3.reset_index(drop=True, inplace=True)

In [53]:
df3.isna().sum()

movie_title       0
Release_Year      0
director_name     9
actor_1_name      9
actor_2_name     16
actor_3_name     32
genres           16
duration          3
language          3
tmdb_score        3
dtype: int64

In [54]:
df3 = df3.dropna(how='any')

In [55]:
df3.isna().sum()

movie_title      0
Release_Year     0
director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
duration         0
language         0
tmdb_score       0
dtype: int64

In [56]:
df3 = df3.rename(columns={'tmdb_score': 'imdb_score'})
df3['movie_title'] = df3['movie_title'].str.lower()

In [57]:
new_df3 = df3.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title','language','duration','imdb_score']]

In [58]:
new_df3

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,language,duration,imdb_score
0,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,"Adventure, Science Fiction, Action",avengers: endgame,English,181.0,8.2
1,Roger Allers,Matthew Broderick,Moira Kelly,Nathan Lane,"Animation, Family, Drama",the lion king,English,89.0,8.3
2,J.J. Abrams,Carrie Fisher,Mark Hamill,Daisy Ridley,"Adventure, Action, Science Fiction",star wars: the rise of skywalker,English,142.0,6.3
4,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,"Family, Comedy, Animation, Adventure",toy story 4,English,100.0,7.5
5,Ryan Fleck,Brie Larson,Samuel L. Jackson,Ben Mendelsohn,"Action, Adventure, Science Fiction",captain marvel,English,124.0,6.8
...,...,...,...,...,...,...,...,...,...
2531,Craig Brewer,Hugh Jackman,Kate Hudson,Michael Imperioli,"Music, Romance, Drama",song sung blue,English,133.0,7.4
2532,Josh Safdie,Timothée Chalamet,Gwyneth Paltrow,Odessa A'zion,"Drama, Thriller",marty supreme,English,150.0,7.4
2533,Mona Fastvold,Amanda Seyfried,Lewis Pullman,Thomasin McKenzie,"History, Drama, Music",the testament of ann lee,English,137.0,6.5
2534,Tony Olmos,Tony Gorodeckas,Noor Razooky,Teresa Suarez Grosso,"Horror, Comedy",continuance,English,89.0,2.5
2535,Reiko Aylesworth,Elizabeth Rodriguez,Jason Butler Harner,Carlease Burke,Drama,i was a stranger,English,17.0,0.0

In [59]:
new_df3['genres'] = new_df3['genres'].str.replace(', ', ' ')
new_df3.head()

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,language,duration,imdb_score
0,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,Adventure Science Fiction Action,avengers: endgame,English,181.0,8.2
1,Roger Allers,Matthew Broderick,Moira Kelly,Nathan Lane,Animation Family Drama,the lion king,English,89.0,8.3
2,J.J. Abrams,Carrie Fisher,Mark Hamill,Daisy Ridley,Adventure Action Science Fiction,star wars: the rise of skywalker,English,142.0,6.3
4,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Family Comedy Animation Adventure,toy story 4,English,100.0,7.5
5,Ryan Fleck,Brie Larson,Samuel L. Jackson,Ben Mendelsohn,Action Adventure Science Fiction,captain marvel,English,124.0,6.8

In [60]:
new_df3['comb'] = new_df3['actor_1_name'] + ' ' + new_df3['actor_2_name'] + ' '+ new_df3['actor_3_name'] + ' '+ new_df3['director_name'] +' ' + new_df3['genres']
new_df3

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,language,duration,imdb_score,comb
0,Joe Russo,Robert Downey Jr.,Chris Evans,Mark Ruffalo,Adventure Science Fiction Action,avengers: endgame,English,181.0,8.2,Robert Downey Jr. Chris Evans Mark Ruffalo Joe...
1,Roger Allers,Matthew Broderick,Moira Kelly,Nathan Lane,Animation Family Drama,the lion king,English,89.0,8.3,Matthew Broderick Moira Kelly Nathan Lane Roge...
2,J.J. Abrams,Carrie Fisher,Mark Hamill,Daisy Ridley,Adventure Action Science Fiction,star wars: the rise of skywalker,English,142.0,6.3,Carrie Fisher Mark Hamill Daisy Ridley J.J. Ab...
4,Josh Cooley,Tom Hanks,Tim Allen,Annie Potts,Family Comedy Animation Adventure,toy story 4,English,100.0,7.5,Tom Hanks Tim Allen Annie Potts Josh Cooley Fa...
5,Ryan Fleck,Brie Larson,Samuel L. Jackson,Ben Mendelsohn,Action Adventure Science Fiction,captain marvel,English,124.0,6.8,Brie Larson Samuel L. Jackson Ben Mendelsohn R...
...,...,...,...,...,...,...,...,...,...,...
2531,Craig Brewer,Hugh Jackman,Kate Hudson,Michael Imperioli,Music Romance Drama,song sung blue,English,133.0,7.4,Hugh Jackman Kate Hudson Michael Imperioli Cra...
2532,Josh Safdie,Timothée Chalamet,Gwyneth Paltrow,Odessa A'zion,Drama Thriller,marty supreme,English,150.0,7.4,Timothée Chalamet Gwyneth Paltrow Odessa A'zio...
2533,Mona Fastvold,Amanda Seyfried,Lewis Pullman,Thomasin McKenzie,History Drama Music,the testament of ann lee,English,137.0,6.5,Amanda Seyfried Lewis Pullman Thomasin McKenzi...
2534,Tony Olmos,Tony Gorodeckas,Noor Razooky,Teresa Suarez Grosso,Horror Comedy,continuance,English,89.0,2.5,Tony Gorodeckas Noor Razooky Teresa Suarez Gro...
2535,Reiko Aylesworth,Elizabeth Rodriguez,Jason Butler Harner,Carlease Burke,Drama,i was a stranger,English,17.0,0.0,Elizabeth Rodriguez Jason Butler Harner Carlea...

In [61]:
final_data = pd.concat([df1, new_df2, new_df3], ignore_index=True)
final_data

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,duration,movie_title,language,imdb_score,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,178.0,avatar,English,7.9,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,169.0,pirates of the caribbean: at world's end,English,7.1,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,148.0,spectre,English,6.8,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,164.0,the dark knight rises,English,8.5,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,0.0,star wars: episode vii - the force awakens ...,unknown,7.1,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...,...,...,...
8097,Craig Brewer,Hugh Jackman,Kate Hudson,Michael Imperioli,Music Romance Drama,133.0,song sung blue,English,7.4,Hugh Jackman Kate Hudson Michael Imperioli Cra...
8098,Josh Safdie,Timothée Chalamet,Gwyneth Paltrow,Odessa A'zion,Drama Thriller,150.0,marty supreme,English,7.4,Timothée Chalamet Gwyneth Paltrow Odessa A'zio...
8099,Mona Fastvold,Amanda Seyfried,Lewis Pullman,Thomasin McKenzie,History Drama Music,137.0,the testament of ann lee,English,6.5,Amanda Seyfried Lewis Pullman Thomasin McKenzi...
8100,Tony Olmos,Tony Gorodeckas,Noor Razooky,Teresa Suarez Grosso,Horror Comedy,89.0,continuance,English,2.5,Tony Gorodeckas Noor Razooky Teresa Suarez Gro...
8101,Reiko Aylesworth,Elizabeth Rodriguez,Jason Butler Harner,Carlease Burke,Drama,17.0,i was a stranger,English,0.0,Elizabeth Rodriguez Jason Butler Harner Carlea...

In [62]:
final_data.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           2
duration         0
movie_title      0
language         0
imdb_score       0
comb             2
dtype: int64

In [63]:
final_data = final_data.dropna(how='any')

In [64]:
final_data.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
duration         0
movie_title      0
language         0
imdb_score       0
comb             0
dtype: int64

In [65]:
final_data.to_csv('datasets/final_data.csv', index=False)